### ISSUE TITLE
部分相机可能存在光机曝光时间设置后，过一段时间失效的问题

### ISSUE THREAD

**Issue by kimkita** [Open3DV/LUMOS#11]
当设置比较长的曝光时间，开始连续采集一会儿，采集程序出现了-13（采集超时）的报错，经过排查，是光机的曝光时间不再是之前设置的值所导致的（在相机采集到前几帧的时候光机就已经投光结束），在另一台机器上并未复现到该问题。

**Comment by xqlong5121** [comment]
get-raw-01-capture部分条纹图是黑的
![image](https://github.com/Open3DV/LUMOS/assets/117330250/ed0ec649-85d9-4485-8732-7d57e3ca2ec4)
此时连接gui再采集一次，就会出现以下现象
![image](https://github.com/Open3DV/LUMOS/assets/117330250/b00ac00b-c5bf-4031-8974-2fa3c03a59cd)

**Comment by kimkita** [comment]
1. 图2中GUI界面的采集出现异常图片是由于相机12bit与8bit在相机采集异常后未正确切换导致，已修复；
2. 肉眼观察到，采集几帧之后，光机的曝光明显较设置的变小，在每次采集之前都设置一次光机曝光时间，未再出现该问题。

**Comment by kimkita** [comment]
光机曝光时间自动变化这个现象，并不是每台机器必现的；在相机采集点云的过程中，2D相机是硬触发采集的，当相机的曝光时间较长（例如40ms），光机的曝光时间较短（例如15ms），就会出现相机采集丢帧的问题（相机1帧的时间，错失了2个触发信号），在程序里体现为相机丢帧无法正常生成点云。
出现这个现象的原因经过确认，是光机的曝光时间自动变化了导致的，当每次采集前都设置一次光机曝光时间，问题就不再复现。

**Comment by kimkita** [comment]
光机曝光自动变化现象的出现频率：正常机器未发生过，异常机器采集3~4次就会复现。
复现方法：固定曝光时间例如50ms采集，触发光机投光（投射预置图像），触发几次过后，光机曝光时间明显变短。
